name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: mgoeppe/shared-workflows/.github/workflows/go-ci.yml@main
    with:
      go-version: "1.24"
      build: true
    permissions:
      contents: read
      id-token: write
